on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        #- macos-11.0
        - macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: neomura/setup-aseprite-cli-action@v1.0.1
    - uses: neomura/setup-avra-cli-action@v1.0.1
    - run: aseprite --help
    - run: avra --help