on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:

    # load your repository.
    - uses: actions/checkout@v2

    # install MSVC - only needed on Windows.
    - uses: ilammy/msvc-dev-cmd@v1

    # install this github action.
    - uses: neomura/setup-aseprite-cli-action@v1

    # aseprite is now available on the path.
    - run: aseprite --help